#
# FindLibMbe.cmake
#

find_path(LIBMBE_INCLUDE_DIR mbelib.h)

set(LIBMBE_NAMES ${LIBMBE_NAMES} mbe libmbe)
find_library(LIBMBE_LIBRARY NAMES ${LIBMBE_NAMES} PATH)

if(LIBMBE_INCLUDE_DIR AND LIBMBE_LIBRARY)
	set(LIBMBE_FOUND TRUE)
endif(LIBMBE_INCLUDE_DIR AND LIBMBE_LIBRARY)

if(LIBMBE_FOUND)
	if(NOT LibMbe_FIND_QUIETLY)
		message(STATUS "Found libmbe: ${LIBMBE_LIBRARY}")
	endif(NOT LibMbe_FIND_QUIETLY)
else(LIBMBE_FOUND)
	if(LibMbe_FIND_REQUIRED)
		message(FATAL_ERROR "Could not find libmbe")
	endif(LibMbe_FIND_REQUIRED)
endif(LIBMBE_FOUND)
